- projects/netgrif-components-core/src/lib/side-menu/services/side-menu.service.ts
Fixes issue from NAB, where clicking the user data field in paper grid editor ends in error, as the side menu component does not exist in NAB.
Fixes [NAE-1575]
No new dependencies was used in this branch.
Tested manually, builded engine for NAB and tried to click it, now the correct message is thrown and not "undefined".
Host OS is macOS Monterey 12.1, the app was running on Angular 10.2.3 with Node 12.22.9 and NPM 6.14.15.
[NAE-1575]: https://netgrif.atlassian.net/browse/NAE-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1575] User select component trying open non-exisisting side menu component

- projects/netgrif-components-core/src/lib/navigation/navigation-drawer/abstract-navigation-drawer.component.spec.ts
- projects/netgrif-components-core/src/lib/navigation/navigation-drawer/abstract-navigation-drawer.component.ts
- projects/netgrif-components/src/lib/navigation/navigation-drawer/navigation-drawer.component.html
- projects/netgrif-components/src/lib/navigation/navigation-drawer/navigation-drawer.component.scss
- added open and close button to drawer
- added support for opening the drawer when its closed due to small width of browser window
Fixes [NAE-1455]
[NAE-1455]: https://netgrif.atlassian.net/browse/NAE-1455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1455] Navigation menu closes on small screens and cannot be reopened

- projects/netgrif-components-core/src/lib/panel/abstract/panel-with-immediate-data.ts
- projects/netgrif-components-core/src/lib/resources/interface/immediate-data.ts
If we choose immediate multichoice or enum map field, there are their keys displayed on case panel instead of their values.
Fixes [NAE-1389]
There are no newly created or imported dependencies.
There are no newly created or imported third party dependencies.
This was tested manually, importing [all_data.xml](https://github.com/netgrif/application-engine/blob/master/src/main/resources/petriNets/all_data.xml) and setting the headers to immediate enum and multichoice map fields.
Host OS is macOS Monterey 12.1, the app was running on Angular 10.2.3 with Node 12.22.9 and NPM 6.14.15.
[NAE-1389]: https://netgrif.atlassian.net/browse/NAE-1389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1389] Immediate map data fields display their keys

- projects/netgrif-components-core/src/lib/configuration/configuration.service.ts
Fixes [NAE-1608]
- fixed return value of getViewByUrl to correct view, if wildcard value is used
Manually tested on example app
| OS                  |Linux Mint 19.3          |
| Runtime             |node v12.16.1           |
| Dependency Manager  |npm 6.14.8           |
| Framework version   |Angular v10           |
[NAE-1608]: https://netgrif.atlassian.net/browse/NAE-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1608] Configuration service getViewByUrl not working with /**

- projects/nae-example-app/src/app/doc/public-resolver/public-resolver.component.ts
- projects/netgrif-components-core/src/lib/authentication/components/abstract-authentication-overlay.ts
- projects/netgrif-components-core/src/lib/groups/services/next-group.service.ts
Fixes [NAE-1592]
- check user$ null value in public resolver
- check user$ null value in abstract authentication overlay
- check user$ null value in next group service
Manually tested on demo application
Manually tested on demo application
| OS                  |Linux Mint 19.3           |
| Runtime             |node v12.16.1           |
| Dependency Manager  |npm 6.14.8          |
| Framework version   |Angular v10           |
[NAE-1592]: https://netgrif.atlassian.net/browse/NAE-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [NAE-1592] UserService user$ observable null value not checked

- projects/netgrif-components/src/lib/panel/panel.component.scss
When a task panel was opened and a text was highlighted in datafield, the user was unable to close the task panel as it did not react to click event. The problem was caused by parent element "mat-sidenav-container", that in google chrome has "user-select" to "none". Fixed with adding explicit user-select: "text" to panel.component.scss
Fixes [NAE-1613]
This was tested manually by clicking in Google Chrome browser.
This was tested on macOS Monterey 12.2.1 using Node 12.22.10 and NPM 6.14.16, implemented using Angular 10.2.3.
[NAE-1613]: https://netgrif.atlassian.net/browse/NAE-1613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1613] Text selection in field value prevents task expansion panel header from reacting to click events

- projects/netgrif-components-core/src/lib/utility/tests/utility/create-mock-net.ts
- projects/netgrif-components-core/src/lib/view/case-view/abstract-case-view.spec.ts
- projects/netgrif-components-core/src/lib/view/case-view/abstract-case-view.ts
- projects/netgrif-components-core/src/lib/view/case-view/service/case-view-service.ts
- update check for createNewCase button
Implements [NAE-1604](https://netgrif.atlassian.net/browse/NAE-1604)
none
none
none
Manual test via example app
| OS                  |      Windows 10     |
| Runtime             |     Node v12.19.0      |
| Dependency Manager  |     npm 6.14.8      |
| Framework version   |           |
> [NAE-1604] - Remove case creation button if there are no nets where user can create an instance

- projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-list-field/enumeration-list-field.component.html
When enumeration list was visible (not editable), the reset button was still clickable.
Fixes [NAE-1628]
This was tested manually using Google Chrome browser.
| Runtime             |  Node 12.22.10         |
| Dependency Manager  |  NPM 6.14.16         |
| Framework version   |  Angular 10.2.3         |
[NAE-1628]: https://netgrif.atlassian.net/browse/NAE-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1628] Reset radio buttons button visible on visible radio buttons

- projects/netgrif-components-core/src/lib/allowed-nets/services/base-allowed-nets.service.ts
- projects/netgrif-components-core/src/lib/allowed-nets/services/factory/allowed-nets-service-factory.ts
Implement use of getters in BaseAllowedNetsService that returns observable instead of the final array of process identifiers.
Implements [NAE-1462]
<Depends on #(PR id)>/<There are no dependencies on other PR>
| Runtime             |  Node 12.22.10         |
| Dependency Manager  |  NPM 6.14.16         |
| Framework version   |  Angular 10.2.3         |
[NAE-1462]: https://netgrif.atlassian.net/browse/NAE-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
> [NAE-1462] Change BaseAllowedNetService to always use observables

- projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.spec.ts
- projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
Fixes [NAE-1435]
- Add check for NaN value in function valueEquality().
No new dependencies
Manual testing
| OS                  | Windows 10 |
| Runtime             | Node 12.18.3 |
| Dependency Manager  | NPM 6.14.6 |
| Framework version   | Angular 10 |
[NAE-1435]: https://netgrif.atlassian.net/browse/NAE-1435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1435] Number field value NaN causes 'Maximum call stack size exceeded'

- projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-dynamic-field/enumeration-autocomplete-dynamic-field.component.html
- projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
- projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-icon-field/enumeration-icon-field.component.html
- projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-select-field/enumeration-select-field.component.html
- added asterisk to required enum fields
Fixes [NAE-1555]
NO tested...  (cherry pick)
| OS                  |           |
| Runtime             |           |
| Dependency Manager  |           |
| Framework version   |           |
[NAE-1555]: https://netgrif.atlassian.net/browse/NAE-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1555] Required select enumeration does not display asterix

- projects/nae-example-app/src/app/doc/public-task-view/public-task-view.component.ts
- projects/netgrif-components-core/src/lib/public/factories/get-net-and-create-case.ts
- projects/netgrif-components-core/src/lib/public/factories/public-search-factory.ts
- projects/netgrif-components-core/src/lib/view/public-api.ts
- projects/netgrif-components-core/src/lib/view/task-view/service/public-task-loading.service.spec.ts
- projects/netgrif-components-core/src/lib/view/task-view/service/public-task-loading.service.ts
Set LoadingEmitter while system creating new case
Fixed [NAE-1381]
none
Assisted testing + manual testing + front-end tests
| OS                  | Windows 10 |
| Runtime             | Node 12.18.3 |
| Dependency Manager  | NPM 6.14.6 |
| Framework version   | Angular 10 |
[NAE-1381]: https://netgrif.atlassian.net/browse/NAE-1381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1381] Public view task loading

- projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
- projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
- projects/netgrif-components-core/src/lib/resources/engine-endpoint/task-resource.service.ts
- projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
Refactoring of error handling so that error messages are displayed on the frontend
Fixes [NAE-1677]
I created net with events on set and get in witch an exception was thrown and after that message from exception showed in snack bar as error.
| OS                  |  Windows 10         |
| Runtime             | Node 14.19.3        |
| Dependency Manager  |  NPM  6.14.17        |
| Framework version   | Angular 13          |
[NAE-1677]: https://netgrif.atlassian.net/browse/NAE-1677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
> [NAE-1677] Message from exception thrown in SET event on data field is not propagated in EventOutcome

- projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
- added update method call to value setter method
Fixes [NAE-1701](https://netgrif.atlassian.net/browse/NAE-1701)
none
Created petri net similar to one where the bug was found.  Replicated the behavior then added fix to code and tested it again.
| OS                  |    Windows 10       |
| Runtime             |      Node v12.18.3     |
| Dependency Manager  |    NPM 6.14.7       |
| Framework version   |    Angular 10.2.3       |
> [NAE-1701] Reload validity on the change required field

- projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
- projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-stepper-field/enumeration-stepper-field.component.scss
When deleting file from file list, set data events were not called.
Fixes [NAE-1626]
This was tested manually and using unit tests.
[NAE-1626]: https://netgrif.atlassian.net/browse/NAE-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1626] Trigger of set event for fileList value deletion is not implemented

- projects/netgrif-components-core/src/lib/search/models/category/case/case-dataset.ts
Incorrect stack of cases were returned when used isNull filter on data in advanced search.  A 'keyword' was missing from the elastic query.
Fixes [NAE-1713]
This was tested manually and using Postman
- <Name of a test [test file](link to the test file)>
[NAE-1713]: https://netgrif.atlassian.net/browse/NAE-1713?atlOrigin=eyJpIjoiNWRkNTljNzYx …
> [NAE-1713] Advanced search searching based on case data does not work

- projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.ts
- projects/netgrif-components/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/multichoice-autocomplete-field.component.html
Implemented resolution of key-value instead of only-value in multichoice map autocomplete.
Fixes [NAE-1738]
No new dependency were introduced.
No new dependency were introduced.
[NAE-1738]: https://netgrif.atlassian.net/browse/NAE-1738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1738] Multichoice map autocomplete init key

- projects/netgrif-components/src/lib/data-fields/boolean-field/boolean-field.component.html
- projects/netgrif-components/src/lib/data-fields/boolean-field/boolean-field.component.scss
Added `<mat-hint>` to boolean field.
Fixes [NAE-1367]
[NAE-1367]: https://netgrif.atlassian.net/browse/NAE-1367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1367] Boolean does not have desc

- projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/abstract-enumeration-autocomplete-select-field.component.ts
- projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-filter-property.ts
- projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.ts
- projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/multichoice-autocomplete-filter-property.ts
- projects/netgrif-components-core/src/lib/data-fields/public-api.ts
- projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
New  property in component
```
<component>
<name>autocomplete</name>
<property key="filter">substring</property>  OR   <property key="filter">prefix</property>
</component>
```
If miss  key="filter"  its  prefix type
Implements [NAE-1751]
[NAE-1751]: https://netgrif.atlassian.net/browse/NAE-1751?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
> [NAE-1751] Autocomplete new  filter "include"

- projects/nae-example-app/src/app/doc/public-workflow-view/public-workflow-view.component.ts
- projects/netgrif-components-core/src/lib/public/factories/get-net-and-create-case.ts
- projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-petri-net-resource.service.ts
Added URL encoding and decoding to public factories, views and services for PetriNet identifiers to support identifiers in URI other than root.
Implements [NAE-1762]
[NAE-1762]: https://netgrif.atlassian.net/browse/NAE-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1762] Public view URL encoding

- projects/netgrif-components-core/src/lib/data-fields/number-field/currency-number-field/abstract-currency-number-field.component.ts
Currency field has a bug, when its value is set to null via actions. The problem is, that on frontend when converting changed value to currency text, the value is only checked for undefined, but not for null. Added check for null value.
Fixes [NAE-1754]
[NAE-1754]: …
> [NAE-1754] Currency field not displaying symbol

- projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
`fileForDownload` is set to undefined on fileField change in AbstractFileFieldComponent.
Fixes [NAE-1763]
| Runtime             |  Java 11        |
| Dependency Manager  |  Maven 3.8.4         |
| Framework version   |  Spring Boot 2.6.2        |
[NAE-1763]: https://netgrif.atlassian.net/browse/NAE-1763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1763] FileField value is not promoted to the frontend after "set data event"

- projects/nae-example-app/src/app/doc/demo-title-config/content/1/demo-title-config-content1-case-view.component.ts
- projects/nae-example-app/src/app/doc/demo-title-config/content/2/demo-title-config-content2-case-view.component.ts
- projects/nae-example-app/src/app/doc/demo-title-config/content/3/demo-title-config-content3-case-view.component.ts
- projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-case-view/tabbed-case-view.component.ts
- projects/netgrif-components-core/src/lib/tabs/classes/tab-view.ts
- projects/netgrif-components-core/src/lib/tabs/interfaces.ts
Save headers on filter tab view using preferences.
Fixes [NAE-1851]
| OS                  |   macOS Ventura 13.1        |
[NAE-1851]: https://netgrif.atlassian.net/browse/NAE-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1851] Save selected headers in filter

- projects/netgrif-components-core/src/lib/search/models/operator/substring.ts
- projects/netgrif-components-core/src/lib/search/search-service/search.service.ts
- replace string ' ' with regex / /g in both substring.ts and search.service.ts
> [NAE-1867] Fulltext replaces only first ' '

- projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
Fixed a bug when expanding assigned task showed us visible field even if it's marked as editable
Fixes [NAE-1869]
This was tested manually, and with unit tests.
| OS                  |     Linux Mint 21.1 Cinnamon      |
| Runtime             |     Node 19.9.0      |
| Dependency Manager  |    NPM 9.6.3       |
| Framework version   |      Angular 13.3.1     |
[NAE-1869]: https://netgrif.atlassian.net/browse/NAE-1869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1869] Incorrectly expanded task

- projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
- projects/netgrif-components-core/src/lib/side-menu/models/side-menu-control.ts
Fixes [NAE-1885]
- sidemenu: create new stream
- newcase: validation isOpened
- newcase: remove title
This was tested manually, and with unit tests.
| OS                  |   macOS Ventura 13.3.1        |
| Runtime             |  Node 18.13.0        |
| Dependency Manager  |  NPM 8.19.3        |
[NAE-1885]: https://netgrif.atlassian.net/browse/NAE-1885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1885] Side panel creates a new case when pressing Enter on date field

- CHANGELOG.md
- projects/netgrif-components-core/src/lib/data-fields/date-field/abstract-date-field.component.spec.ts
- projects/netgrif-components-core/src/lib/data-fields/date-field/abstract-date-field.component.ts
- projects/netgrif-components-core/src/lib/data-fields/date-time-field/abstract-date-time-field.component.spec.ts
- projects/netgrif-components-core/src/lib/data-fields/date-time-field/abstract-date-time-field.component.ts
- projects/netgrif-components-core/src/lib/data-fields/time-instance-abstract-field/abstract-time-instance-field.component.ts
- projects/netgrif-components-core/src/lib/data-fields/time-instance-abstract-field/models/abstract-time-instance-field.ts
- projects/netgrif-components/src/lib/data-fields/date-field/date-field.component.ts
- projects/netgrif-components/src/lib/data-fields/date-time-field/date-time-field.component.spec.ts
- projects/netgrif-components/src/lib/data-fields/date-time-field/date-time-field.component.ts
- add locale to date fields (needed in datetime field)
- rework of validations from weekday to isoWeekday
Fixes [NAE-1923]
none
manually
| OS                  |  LINUX MINT  20.3       |
| Runtime             |    NodeJS 14.21.3       |
| Dependency Manager  |    NPM  6.14.18      |
[NAE-1923]: https://netgrif.atlassian.net/browse/NAE-1923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1923] DateTime doesn't have locale and rework validation to isoWeekday

- projects/netgrif-components-core/src/lib/data-fields/models/component.ts
- projects/netgrif-components-core/src/lib/data-fields/public-api.ts
- projects/netgrif-components-core/src/lib/data-fields/string-collection-field/models/string-collection-field.ts
- projects/netgrif-components-core/src/lib/data-fields/string-collection-field/string-collection-default-field/abstract-string-collection-default-field.component.ts
- projects/netgrif-components-core/src/lib/task-content/model/field-type-resource.ts
- projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
- projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
- projects/netgrif-components/src/lib/data-fields/data-fields.module.ts
- projects/netgrif-components/src/lib/data-fields/string-collection-field/string-collection-default-field/string-collection-default-field.component.html
- projects/netgrif-components/src/lib/data-fields/string-collection-field/string-collection-default-field/string-collection-default-field.component.scss
- projects/netgrif-components/src/lib/data-fields/string-collection-field/string-collection-default-field/string-collection-default-field.component.spec.ts
- projects/netgrif-components/src/lib/data-fields/string-collection-field/string-collection-default-field/string-collection-default-field.component.ts
- add new datafield stringCollection and implement it as chip list
Implements [NAE-1929]
none
manual
| OS                  |  Linux Mint 20         |
| Runtime             |     NodeJS 14.21.3     |
| Dependency Manager  |    NPM 6.14.18       |
| Framework version   |     Angular 13     |
[NAE-1929]: https://netgrif.atlassian.net/browse/NAE-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1929] Data field type list of strings

- projects/netgrif-components-core/src/lib/authentication/services/authentication/authentication.service.ts
- projects/netgrif-components-core/src/lib/data-fields/file-list-field/file-list-default-field/abstract-file-list-default-field.component.ts
- projects/netgrif-components-core/src/lib/navigation/quick-panel/components/language-selector/abstract-language-selector.component.spec.ts
- projects/netgrif-components-core/src/lib/side-menu/side-menu-container/abstract-side-menu-container.component.spec.ts
- projects/netgrif-components-core/src/lib/task/services/task-data.service.spec.ts
- projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-authentication.service.ts
- projects/netgrif-components-core/src/lib/view/case-view/components/case-list/abstract-case-list.component.spec.ts
- projects/netgrif-components/src/lib/admin/user-invite/user-invite.component.scss
- projects/netgrif-components/src/lib/dialog/filter-selector-dialog/filter-selector-dialog.component.ts
- projects/netgrif-components/src/lib/dialog/import-net-dialog/import-net-dialog.component.scss
- projects/netgrif-components/src/lib/panel/task-panel-list/task-list.component.spec.ts
- projects/netgrif-components/src/lib/side-menu/content-components/multi-user-assign/multi-user-assign-list/multi-user-assign-list.component.spec.ts
- projects/netgrif-components/src/lib/side-menu/content-components/user-assign/user-assign-list/user-assign-list.component.spec.ts
- projects/netgrif-components/src/lib/tabs/tab-view/tab-view.component.spec.ts
Fixes [NAE-1939]
none
manually
| OS                  |   linux mint 20       |
| Runtime             |      NodeJS 14     |
| Dependency Manager  |     npm 6      |
| Framework version   |     angular 13      |
[NAE-1939]: https://netgrif.atlassian.net/browse/NAE-1939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1939] Problem with Tests

- docs/_sidebar.md
- docs/views/default-tabbed-case-view.md
- projects/netgrif-components-core/src/lib/navigation/model/group-navigation-constants.ts
- projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/model/new-case-injection-data.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tab-view/default-tab-view.component.spec.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tab-view/default-tab-view.component.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.html
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.ts
- added param to default-case-view and default-tab-view that checks if create case button is shown
Implements [NAE-1936]
Tested manually.
| OS                  |     Windows      |
| Runtime             |    Node 16.13.0      |
| Dependency Manager  |   Npm 8.1.0       |
| Framework version   |      Angular 13.3.1     |
[NAE-1936]: https://netgrif.atlassian.net/browse/NAE-1936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1936] Disable create case button using menu items

- projects/netgrif-components-core/src/lib/data-fields/case-ref-field/case-ref-default/case-ref-default.component.ts
- projects/netgrif-components-core/src/lib/data-fields/case-ref-field/model/abstract-case-ref-base-field-component.ts
- projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-caseref-field/abstract-enumeration-caseref-field.component.ts
- projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-caseref-field/abstract-multichoice-caseref-field.component.ts
- add parsing a filter from properties
Implements [NAE-1957]
none
manually
| OS                  |     Linux Mint 20      |
[NAE-1957]: https://netgrif.atlassian.net/browse/NAE-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1957] Allow filter to caseRef field and variants

- projects/netgrif-components-core/src/lib/data-fields/user-field/user-default-field/abstract-user-default-field.component.ts
- projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.spec.ts
- projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
- projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
- projects/netgrif-components/src/lib/data-fields/file-list-field/file-list-default-field/file-list-default-field.component.html
- projects/netgrif-components/src/lib/data-fields/file-list-field/file-list-default-field/file-list-default-field.component.scss
- projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-text-field/i18n-text-field.component.scss
- fix the problem with null value on enum and autocomplete enum
- fix the scrollbar of filelist field
- fix the scrollbar on i18n field
Fixes [NAE-1960]
none
manually
| OS                  |      Linux Mint 20     |
| Dependency Manager  |       NPM 10.2.4    |
| Framework version   |       Angular 13    |
[NAE-1960]: https://netgrif.atlassian.net/browse/NAE-1960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1960] Enumeration Map does not propagate changes when selecting 

- projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-task-resource.service.ts
- fix the problem
Fixes [NAE-1983]
none
tested manually
| OS                  |     LinuxMint 20     |
[NAE-1983]: …
> [NAE-1983] Public view file handling

- projects/netgrif-components-core/src/lib/data-fields/file-field/file-default-field/abstract-file-default-field.component.ts
- projects/netgrif-components-core/src/lib/data-fields/file-list-field/file-list-default-field/abstract-file-list-default-field.component.ts
- projects/netgrif-components-core/src/lib/data-fields/models/abstract-file-field-default-component.ts
- fix the problem with showing byte size in snackbar, changed to MB, add message as property
Fixes [NAE-1949]
none
manually
| OS                  |      LinuxMint 20     |
[NAE-1949]: https://netgrif.atlassian.net/browse/NAE-1949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-1949] Allowed Types for Filefield

- projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
- fix the issue with resolving of referenced field's changes
Fixes [NAE-2005]
none
manually
| OS                  |      LinuxMint 20     |
[NAE-2005]: …
> [NAE-2005] Field behavior change does not work correctly with multiple references using taskRef

- CHANGELOG.md
- package.json
- projects/netgrif-components-core/package.json
- projects/netgrif-components-core/src/lib/navigation/breadcrumbs/abstract-breadcrumbs.component.ts
- projects/netgrif-components-core/src/lib/navigation/model/navigation-menu-events.ts
- projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
- projects/netgrif-components-core/src/lib/navigation/navigation-drawer/abstract-navigation-drawer.component.ts
- projects/netgrif-components-core/src/lib/navigation/public-api.ts
- projects/netgrif-components-core/src/lib/navigation/quick-panel/components/logout-shortcut/abstract-logout-shortcut.component.ts
- projects/netgrif-components/package.json
Added outputs to navigation components, mainly to navigation menus (i.e. double-drawer menu), for better event reaction in the final app.
Implements [NAE-2021]
Tested on examples project in the mono-repo.
| OS                  |        Linux   |
| Runtime             |          NodeJS 20 |
| Dependency Manager  |         NPM 10  |
| Framework version   |       Angular 13    |
[NAE-2021]: https://netgrif.atlassian.net/browse/NAE-2021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAE-2021] Outputs for navigation components

- nae.json
- projects/netgrif-components-core/src/commons/schema.ts
- projects/netgrif-components-core/src/lib/navigation/model/group-navigation-constants.ts
- projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.spec.ts
- projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
- projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/service/double-drawer-navigation.service.ts
- projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/util/double-drawer-utils.ts
- projects/netgrif-components-core/src/lib/navigation/public-api.ts
- projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.html
- projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.ts
Implemented rule, that selects particular view of the menu item when clicked on folder or initialized menu. Also moved the code, that load and navigates through the menu in separate service and utils. This service holds the menu resources.
Implements [NAE-2034]
No dependency
Manually and by tests
| OS                  |  Ubuntu 24.04.1 LTS |
| Runtime             |  Java 11  |
| Dependency Manager  |   Maven 3.6.3  |
| Framework version   |    Spring Boot 2.7.8  |
[NAE-2034]: https://netgrif.atlassian.net/browse/NAE-2034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
> [NAE-2034] Open first view

- nae.json
- projects/nae-example-app/src/app/nae-example-app-view.service.ts
- projects/netgrif-components-core/src/lib/allowed-nets/services/factory/allowed-nets-service-factory.ts
- projects/netgrif-components-core/src/lib/navigation/utility/filter-extraction.service.ts
- projects/netgrif-components-core/src/lib/utility/navigation-item-task-filter-factory.ts
- projects/netgrif-components-core/src/lib/utility/navigation-item-task-search-categories-factory.ts
- projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-caseref-field/enumeration-caseref-field.component.spec.ts
- projects/netgrif-components/src/lib/data-fields/multichoice-field/multichoice-caseref-field/multichoice-caseref-field.component.spec.ts
- projects/netgrif-components/src/lib/data-fields/task-ref-field/task-ref-list-field/task-ref-list-field.component.spec.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-simple-task-view/default-simple-task-view.component.html
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-simple-task-view/default-simple-task-view.component.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tab-view/default-tab-view.component.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-task-view/default-task-view.component.spec.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/model/factory-methods.ts
Implements possibility to navigate to task list view of case which caseId is included in URL. Only tasks of this case are displayed in this task list view. This view needs to be included in nae.json and registered in view.service of project. See example in code.
Implements [NAE-2036]
Manually from application
| OS                  |     Linux Mint 21      |
| Runtime             |      Node 20.13.1     |
| Dependency Manager  |     npm 10.8.0      |
| Framework version   |    Angular 13.3.1      |
[NAE-2036]: …
> [NAE-2036] Task-List-View to open Case by link

- projects/netgrif-components-core/src/lib/navigation/utility/filter-extraction.service.ts
- projects/netgrif-components-core/src/lib/search/search-service/search.service.ts
- projects/netgrif-components-core/src/lib/utility/navigation-item-task-filter-factory.ts
- projects/netgrif-components/src/lib/data-fields/file-field/file-default-field/file-default-field.component.html
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-case-ref-list-view/default-case-ref-list-view.component.html
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-case-ref-list-view/default-case-ref-list-view.component.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/model/factory-methods.ts
Implements option to load filter from advanced search for caseRef component fields:
- caseRef field default view
- multichoice caseref component view
- enumeration caseref component view
Fix loading of filters in default-tabbed-view.
Implementation for release 6.4.1
Implements [NAE-2056] 
Manually from application
| OS                  |     Linux Mint 21      |
| Runtime             |      Node 20.13.1      |
| Dependency Manager  |    npm  10.8.0    |
| Framework version   |    Angular 13.3.1       |
[NAE-2056]: …
> [NAE-2056] Fix NAE-2048 in release 6.4.1

- projects/netgrif-components-core/src/assets/i18n/de.json
- projects/netgrif-components-core/src/assets/i18n/en.json
- projects/netgrif-components-core/src/assets/i18n/sk.json
- projects/netgrif-components-core/src/lib/export/public-api.ts
- projects/netgrif-components-core/src/lib/export/services/export.service.spec.ts
- projects/netgrif-components-core/src/lib/export/services/export.service.ts
- projects/netgrif-components-core/src/lib/navigation/model/group-navigation-constants.ts
- projects/netgrif-components-core/src/public-api.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tab-view/default-tab-view.component.spec.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tab-view/default-tab-view.component.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.html
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.scss
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.spec.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/default-tabbed-case-view/default-tabbed-case-view.component.ts
- projects/netgrif-components/src/lib/navigation/group-navigation-component-resolver/default-components/model/injected-tabbed-case-view-data-with-navigation-item-task-data.ts
- implement exporting cases from case view
- add export service
- add attribute allow export to default tab view and default tabbed case view
- add export button to default tabbed case view
Implementation of export cases from case view functionality
Implements [NAE-2100]
Depends on [Application Engine PR](https://github.com/netgrif/application-engine/pull/307)
Manually
| OS                  | Fedora |
| Runtime             |           |
| Dependency Manager  |           |
| Framework version   |           |
[NAE-2100]: https://netgrif.atlassian.net/browse/NAE-2100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
> NAE-2100 - Case view export button as NAE feature
