projects/netgrif-components-core/src/lib/authorization/permission/permission.service.spec.ts
projects/netgrif-components-core/src/lib/authorization/permission/permission.service.ts

- fix permission check
- Fixes [NAE-1574]
- There are no dependencies on other PR
- [should test hasNetPermission](https://github.com/netgrif/components/blob/88b082a4a9f6e8f713ba27f7610e1e88c5c56f5c/projects/netgrif-components-core/src/lib/authorization/permission/permission.service.spec.ts)
- Linux Mint 19.3
- Default application …

[NAE-1574] Net role permission checking

---

projects/netgrif-components-core/src/assets/i18n/sk.json

- check slovak
Fixes [NAE-1580]
[NAE-1580]: https://netgrif.atlassian.net/browse/NAE-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1580] Grammar check

---

projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-list-field/abstract-enumeration-list-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/enumeration-field/models/enumeration-field.ts
projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-dynamic-field/enumeration-autocomplete-dynamic-field.component.html
projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-list-field/enumeration-list-field.component.html
projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-select-field/enumeration-select-field.component.html

- implemented resetEnum function
- added translations for mat-button of resetting enum
- added null value to dropdown enums
- added reset button to list enum
- added null applying to enums
Fixes [NAE-1557]
[NAE-1557]: https://netgrif.atlassian.net/browse/NAE-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1557] Cannot clear optional enumeration

---

projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts

Fixes issue when a field's behaviour is changed in task reference and this change did not apply. It is fixed via requesting reload on the referenced task.
Fixes: [NAE-1577]
No new dependencies was used, imported or implemented.
No new third party dependencies was used, imported or implemented.
Tested it using the provided Petri Net files in Jira issue [NAE-1577]. I imported the Petri Nets into the application engine, and using example app and followed the reproduction steps that where described in Jira issue.
Host OS is macOS Monterey 12.1, the app was running on Angular 10.2.3 with Node 12.22.9 and NPM 6.14.15.
[NAE-1577]: https://netgrif.atlassian.net/browse/NAE-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

[NAE-1577] Task reffed change behavior does not propagate

---

projects/netgrif-components-core/src/lib/header/case-header/case-header.service.ts
projects/netgrif-components-core/src/lib/search/models/category/no-configuration-user-autocomplete-category.ts

- fixed header search by author
Fixes [NAE-1524]
[NAE-1524]: https://netgrif.atlassian.net/browse/NAE-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1524] Header search by author is not working

---

projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts

- added listener for layout change in abstract-data-field.ts
Fixes [NAE-1472]
[NAE-1472]: https://netgrif.atlassian.net/browse/NAE-1472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1472] MaterialAppearance property on AbstractDataField

---

projects/nae-example-app/src/app/doc/forms/email-form/password-form.component.html
projects/nae-example-app/src/app/doc/forms/email-form/password-form.component.ts
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components-core/src/lib/forms/email-submission/abstract-email-submission-form.component.spec.ts
projects/netgrif-components-core/src/lib/forms/email-submission/abstract-email-submission-form.component.ts
projects/netgrif-components-core/src/lib/forms/models/abstract-registration.component.ts
projects/netgrif-components/src/lib/forms/email-submission/email-submission-form.component.html
projects/netgrif-components/src/lib/forms/forgotten-password/forgotten-password-form.component.html
projects/netgrif-components/src/lib/forms/registration/registration-form.component.html

- added input observable to abstract-email-submission-form.component.ts
- added spinner to submit button on signup-or-reset
- resolved loading emmiter in password-form.component.ts
Fixes [NAE-1459]
[NAE-1459]: https://netgrif.atlassian.net/browse/NAE-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1459] Loading indicator on login and registration related components

---

projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts

Fixes [NAE-1583]
- fix FileField/FileListField placeholder
Manually tested 
Manually tested 
[NAE-1583]: https://netgrif.atlassian.net/browse/NAE-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1583] Broken FileField/FileListField placeholder

---

projects/netgrif-components/src/lib/navigation/navigation-drawer/navigation-drawer.component.scss

Fixes [NAE-1586]
- fix broken virtual scroll
- Not needed
- Not needed
[NAE-1586]: https://netgrif.atlassian.net/browse/NAE-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1586] Virtual scroll is broken everywhere on page

---

projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts

- resolve Parent Task Id
Fixes [NAE-1601]
| Runtime             |  Node v12.22.11         |
| Dependency Manager  |   NPM 6.14.16      |
| Framework version   |    Angular 10.2.3       |
[NAE-1601]: https://netgrif.atlassian.net/browse/NAE-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1601] Component preview field is not propagated into taskRef

---

projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
projects/netgrif-components/src/lib/side-menu/content-components/new-case/new-case.component.html

- resolve Parent Task Id
Fixes [NAE-1597]
| Runtime             |  Node v12.22.11         |
| Dependency Manager  |   NPM 6.14.16      |
| Framework version   |    Angular 10.2.3       |
[NAE-1597]: https://netgrif.atlassian.net/browse/NAE-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1597] New case process input is not validated

---

projects/nae-example-app/src/app/doc/case-view/case-view.component.html
projects/nae-example-app/src/app/doc/case-view/case-view.component.scss
projects/nae-example-app/src/app/doc/task-view/task-view.component.html
projects/netgrif-components-core/src/lib/panel/public-api.ts
projects/netgrif-components-core/src/lib/panel/task-panel-list/abstract-task-list.component.ts
projects/netgrif-components-core/src/lib/panel/task-panel-list/default-task-panel-list/abstract-default-task-list.ts
projects/netgrif-components-core/src/lib/panel/task-panel-list/task-panel-list-pagination/abstract-task-list-pagination.component.ts
projects/netgrif-components-core/src/lib/view/case-view/components/case-list-paginator/abstract-case-list-paginator.component.spec.ts
projects/netgrif-components-core/src/lib/view/case-view/components/case-list-paginator/abstract-case-list-paginator.component.ts
projects/netgrif-components-core/src/lib/view/case-view/components/case-list/abstract-case-list.component.ts
projects/netgrif-components-core/src/lib/view/case-view/components/default-case-list/abstract-default-case-list.ts
projects/netgrif-components-core/src/lib/view/case-view/service/case-view-service.ts
projects/netgrif-components-core/src/lib/view/public-api.ts
projects/netgrif-components-core/src/lib/view/task-view/service/task-view.service.ts
projects/netgrif-components/src/lib/panel/panel.module.ts
projects/netgrif-components/src/lib/panel/public-api.ts
projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.html
projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.scss
projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.spec.ts
projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.ts
projects/netgrif-components/src/lib/view/case-view/case-view.module.ts
projects/netgrif-components/src/lib/view/case-view/components/case-list-paginator/case-list-paginator.component.html
projects/netgrif-components/src/lib/view/case-view/components/case-list-paginator/case-list-paginator.component.scss
projects/netgrif-components/src/lib/view/case-view/components/case-list-paginator/case-list-paginator.component.spec.ts
projects/netgrif-components/src/lib/view/case-view/components/case-list-paginator/case-list-paginator.component.ts
projects/netgrif-components/src/lib/view/case-view/components/case-list/case-list.component.ts

Create new case list component with pagination footer
Implements [NAE-1061]
none
manually
| OS                  |    Linux Mint 20       |
| Runtime             |  Node 14.19.1         |
| Dependency Manager  |  NPM 6.14.16         |
| Framework version   |  Angular 10     |
[NAE-1061]: https://netgrif.atlassian.net/browse/NAE-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1061] Resource pagination with paginator footer 

---

projects/netgrif-components-core/src/lib/panel/abstract/panel-with-header-binding.ts
projects/netgrif-components-core/src/lib/panel/panel-item/abstract-panel-item.component.spec.ts
projects/netgrif-components-core/src/lib/panel/panel-item/abstract-panel-item.component.ts
projects/netgrif-components-core/src/lib/panel/public-api.ts
projects/netgrif-components/src/lib/panel/case-panel/case-panel.component.html
projects/netgrif-components/src/lib/panel/panel-item/panel-item.component.html
projects/netgrif-components/src/lib/panel/panel-item/panel-item.component.scss
projects/netgrif-components/src/lib/panel/panel-item/panel-item.component.spec.ts
projects/netgrif-components/src/lib/panel/panel-item/panel-item.component.ts
projects/netgrif-components/src/lib/panel/panel.module.ts
projects/netgrif-components/src/lib/panel/public-api.ts
projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.html

Multiple implementations existed of the same column resolution in task-panel and case-panel. Now, there is a new component created that implements the logic only once.
Implements [NAE-1363]
Pull request #43 is needed to be finished first to upgrade the new component to Angular 13 paradigm.
This was tested manually and via unit tests.
| Runtime             |  Node 12.22.10         |
| Dependency Manager  |  NPM 6.14.16         |
| Framework version   |  Angular 10.2.3         |
[NAE-1363]: …

[NAE-1363] Refactor panel featured values

---

projects/netgrif-components/src/lib/panel/panel.module.ts

- export PanelItemComponent (panel.module)
Fixes [NAE-1656]
This was tested manually and using Unit tests. …

[NAE-1656] Export  nc-panel-item

---

projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components/src/lib/data-fields/user-field/user-field.component.html

Implemented translation for user field label.
Implements [NAE-1667]
[NAE-1667]: https://netgrif.atlassian.net/browse/NAE-1667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

[NAE-1667] Select user translation

---

projects/netgrif-components-core/src/lib/search/models/category/case/case-dataset.ts
projects/netgrif-components-core/src/lib/search/models/category/case/case-simple-dataset.ts

Implement Elastisearch mapping for I18nField for better filtering for translations.
Implements [NAE-1647]
| Framework version   |  Angular 10.2.3         |
[NAE-1647]: https://netgrif.atlassian.net/browse/NAE-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1647] Elastic mapping for I18N data field

---

projects/netgrif-components-core/src/lib/header/header-modes/search-mode/abstract-search-mode.component.ts
projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
projects/netgrif-components/src/lib/header/header-modes/search-mode/search-mode.component.html
projects/netgrif-components/src/lib/header/header.theme.scss
projects/netgrif-components/src/lib/tabs/tabs.module.ts

Redesign header search mode
Fixes [NAE-1669]
[NAE-1669]: https://netgrif.atlassian.net/browse/NAE-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1669] Fix header design

---

nae.json
projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components-core/src/lib/authorization/permission/access.service.spec.ts
projects/netgrif-components-core/src/lib/authorization/permission/access.service.ts
projects/netgrif-components-core/src/lib/authorization/public-api.ts
projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
projects/netgrif-components-core/src/lib/navigation/navigation-tree/abstract-navigation-tree.component.spec.ts
projects/netgrif-components-core/src/lib/navigation/navigation-tree/abstract-navigation-tree.component.ts
projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.html
projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.spec.ts
projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.ts
projects/netgrif-components/src/lib/navigation/navigation-tree/navigation-tree.component.ts
projects/netgrif-components/src/lib/navigation/public-api.ts

Added more refinements to the two-level menu, like sorting, more configuration options and permission checks.
Implements [NAE-1658]
Manually on several use-cases of different configurations.
| OS                  |    Windows 11       |
| Runtime             |  NodeJs 16         |
| Dependency Manager  | NPM 8          |
| Framework version   |   Angular 13        |
| Run parameters      |    -       |
| Other configuration |    -       |
[NAE-1658]: https://netgrif.atlassian.net/browse/NAE-1658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1658] Two-level navigation menu

---

projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-task-view/tabbed-task-view.component.ts
projects/netgrif-components-core/src/lib/tabs/classes/opened-tab.ts
projects/netgrif-components-core/src/lib/tabs/classes/tab-label-stream.ts
projects/netgrif-components-core/src/lib/tabs/classes/tab-view.ts
projects/netgrif-components-core/src/lib/tabs/interfaces.ts
projects/netgrif-components-core/src/lib/tabs/public-api.ts
projects/netgrif-components-core/src/lib/task-content/model/task-event-notification.ts
projects/netgrif-components-core/src/lib/task/services/assign-task.service.ts
projects/netgrif-components-core/src/lib/task/services/cancel-task.service.ts
projects/netgrif-components-core/src/lib/task/services/delegate-task.service.ts
projects/netgrif-components-core/src/lib/task/services/finish-task.service.ts
projects/netgrif-components-core/src/lib/view/case-view/tabbed-case-view.ts
projects/netgrif-components/src/lib/tabs/tab-view/tab-view.component.html

Implements [NAE-1671]
[NAE-1671]: https://netgrif.atlassian.net/browse/NAE-1671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1671] Dynamic case title in tab

---

nae.json
projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.html
projects/netgrif-components/src/lib/admin/role-assignment/role-assignment.component.html
projects/netgrif-components/src/lib/data-fields/text-field/html-textarea-field/html-textarea-field.component.html
projects/netgrif-components/src/lib/data-fields/text-field/html-textarea-field/html-textarea-field.component.ts

- translate text
Implements [NAE-1682]
[NAE-1682]: https://netgrif.atlassian.net/browse/NAE-1682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1682] Translate tooltip admin view

---

projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.ts
projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-task-resource.service.ts

There was missing code in public-task-resource.service.ts file, which is present in normal task-resource.service.ts. 
Fixes [NAE-1680]
[NAE-1680]: https://netgrif.atlassian.net/browse/NAE-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1680] Public view + change behavior bug

---

projects/netgrif-components-core/src/lib/task-content/field-component-resolver/abstract-field-component-resolver.component.ts
projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts

If file field is referenced through taskRef, it was not possible to delete file, because it references to parent task.
Fixes [NAE-1681]
Depends on #86
[NAE-1681]: https://netgrif.atlassian.net/browse/NAE-1681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1681] Delete file function works with parent task in taskRef-ed file field.

---

projects/nae-example-app/src/app/doc/case-view/case-view.component.ts
projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-case-view/tabbed-case-view.component.ts
projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-task-view/tabbed-task-view.component.ts
projects/nae-example-app/src/app/doc/task-view/task-view.component.ts
projects/netgrif-components-core/src/lib/header/abstract-header-service.ts
projects/netgrif-components-core/src/lib/header/abstract-header.component.ts
projects/netgrif-components-core/src/lib/header/services/overflow.service.ts
projects/netgrif-components-core/src/lib/panel/abstract/panel-with-header-binding.ts
projects/netgrif-components-core/src/lib/panel/abstract/panel-with-immediate-data.ts
projects/netgrif-components-core/src/lib/panel/case-panel/abstract-case-panel.component.spec.ts
projects/netgrif-components-core/src/lib/panel/case-panel/abstract-case-panel.component.ts
projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
projects/netgrif-components-core/src/lib/panel/workflow-panel/abstract-workflow-panel.component.ts
projects/netgrif-components/src/lib/panel/case-panel/case-panel.component.ts
projects/netgrif-components/src/lib/panel/public-workflow-panel/public-workflow-panel.component.ts
projects/netgrif-components/src/lib/panel/task-panel/task-panel.component.ts
projects/netgrif-components/src/lib/panel/workflow-panel/workflow-panel.component.ts

⚠️ extend constructor with overflowService ⚠️
Fixes [NAE-1690]
[NAE-1690]: https://netgrif.atlassian.net/browse/NAE-1690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1690] Fix header responsive  overflow mode

---

projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts

- change file response
Fixes [NAE-1677]
[NAE-1677]: https://netgrif.atlassian.net/browse/NAE-1677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1677] Message from exception thrown in SET event on data field is not propagated in EventOutcome

---

.github/PULL_REQUEST_TEMPLATE.md
projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts

Fixes [NAE-1701]
[NAE-1701]: https://netgrif.atlassian.net/browse/NAE-1701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1701] Reload validity on the change required field 

---

nae.json
projects/nae-example-app/src/app/doc/case-view/case-view.component.scss
projects/nae-example-app/src/app/doc/public-resolver/public-resolver.component.spec.ts
projects/nae-example-app/src/app/doc/public-single-task-view/public-single-task-view.component.spec.ts
projects/nae-example-app/src/app/doc/public-task-view/public-task-view.component.scss
projects/nae-example-app/src/app/doc/public-task-view/public-task-view.component.spec.ts
projects/nae-example-app/src/app/doc/public-workflow-view/public-workflow-view.component.scss
projects/nae-example-app/src/app/doc/public-workflow-view/public-workflow-view.component.spec.ts
projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-case-view/tabbed-case-view.component.scss
projects/nae-example-app/src/app/doc/tabbed-case-view/tabbed-task-view/tabbed-task-view.component.scss
projects/nae-example-app/src/app/doc/task-view/task-view.component.scss
projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/create-case-view.ts
projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/common/__className@dasherize__.component.html.template
projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/common/__className@dasherize__.component.spec.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/simple/__className@dasherize__.component.scss.template
projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/simple/__className@dasherize__.component.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/tabbed/__className@dasherize__.component.scss.template
projects/netgrif-components/schematics/view/create-view-prompt/views/case-view/files/tabbed/__className@dasherize__.component.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/dashboard-view/create-dashboard-view.ts
projects/netgrif-components/schematics/view/create-view-prompt/views/dashboard-view/files/__className@dasherize__.component.spec.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/group-view/files/__className@dasherize__.component.scss.template
projects/netgrif-components/schematics/view/create-view-prompt/views/group-view/files/__className@dasherize__.component.spec.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/public-resolver-view/files/common/__className@dasherize__.component.spec.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/public-single-task-view/files/common/__className@dasherize__.component.spec.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/public-single-task-view/files/common/__className@dasherize__.component.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/public-task-view/files/common/__className@dasherize__.component.spec.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/public-task-view/files/common/__className@dasherize__.component.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/public-workflow-view/files/common/__className@dasherize__.component.spec.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/task-view/files/common/__className@dasherize__.component.spec.ts.template
projects/netgrif-components/schematics/view/create-view-prompt/views/task-view/files/simple/__className@dasherize__.component.ts.template

- fix tests int generated schematics, and also fix the problems with generated files
- fix som of the css styles
Implements [NAE-1695]
none
Depends on #92 
manually with schematics in project
| OS                  |   Linux Mint        |
| Runtime             |   NodeJS        |
| Dependency Manager  |    NPM       |
| Framework version   |   ANgular 13        |
[NAE-1695]: https://netgrif.atlassian.net/browse/NAE-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1695] Fix generated tests in schematics

---

projects/netgrif-components-core/src/lib/search/search-operand-input-component/abstract-search-operand-input.component.ts
projects/netgrif-components/src/lib/search/advanced-search/search-operand-input-component/search-operand-input.component.html

- fix change to function
Fixes [NAE-1712]
[NAE-1712]: https://netgrif.atlassian.net/browse/NAE-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1712] Advanced search in case of date operators is blinking (very quickly opening and closing)

---

projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts

- handle error
Implements [NAE-1721]
none
manually
| OS                  |     Linux Mint      |
| Runtime             |     NodeJS     |
| Dependency Manager  |     NPM      |
| Framework version   |     Andular 13.2      |
[NAE-1721]: https://netgrif.atlassian.net/browse/NAE-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1721] Create case event bad handling on frontend

---

.github/config.yml
CHANGELOG.md
package.json
projects/netgrif-components-core/package.json
projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components-core/src/commons/schema.ts
projects/netgrif-components-core/src/lib/authorization/permission/access.service.ts
projects/netgrif-components-core/src/lib/authorization/role/role-guard.service.spec.ts
projects/netgrif-components-core/src/lib/authorization/role/role-guard.service.ts
projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/file-list-field/abstract-file-list-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/number-field/currency-number-field/abstract-currency-number-field.component.ts
projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.spec.ts
projects/netgrif-components-core/src/lib/navigation/navigation-double-drawer/abstract-navigation-double-drawer.ts
projects/netgrif-components-core/src/lib/navigation/service/uri.service.spec.ts
projects/netgrif-components-core/src/lib/resources/engine-endpoint/task-resource.service.ts
projects/netgrif-components-core/src/lib/search/models/category/case/case-dataset.ts
projects/netgrif-components-core/src/lib/search/search-operand-input-component/abstract-search-operand-input.component.ts
projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
projects/netgrif-components-core/src/lib/task-content/field-component-resolver/abstract-field-component-resolver.component.ts
projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-uri-resource.service.ts
projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-user.service.ts
projects/netgrif-components/package.json
projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html
projects/netgrif-components/src/lib/search/advanced-search/search-operand-input-component/search-operand-input.component.html

- [NAE-1693] TaskController deleteFile endpoint lacks data about tasks
- [NAE-1712] Advanced search in case of date operators is blinking (very quickly opening and closing)
- [NAE-1713] Advanced search searching based on case data does not work
- [NAE-1715] Currency component not working properly
- [NAE-1716] Autocomplete component not working properly on enumeration_map field
- [NAE-1717] Banned roles not hiding menu entries
- [NAE-1721] Create case event bad handling on frontend
- [NAE-1724] Incorrect german translation
[NAE-1693]: https://netgrif.atlassian.net/browse/NAE-1693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NAE-1712]: https://netgrif.atlassian.net/browse/NAE-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …

Release 6.2.2

---

package.json

Fixes [NAE-1731]
[NAE-1731]: https://netgrif.atlassian.net/browse/NAE-1731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1731] Missing write access to /home/.../node_modules/@netgrif/components

---

projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.html

- fix
Fixes [NAE-1732]
[NAE-1732]: https://netgrif.atlassian.net/browse/NAE-1732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1732] LDAP group role assignment component tile tooltip

---

projects/netgrif-components-core/src/lib/authentication/components/abstract-authentication-overlay.ts

Fixed stuck overlay on login page.
Fixes [NAE-1734]
[NAE-1734]: https://netgrif.atlassian.net/browse/NAE-1734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

[NAE-1734] Overlay on login page

---

projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-text-field/i18n-text-field.component.html

Fixes [NAE-1737]
[NAE-1737]: https://netgrif.atlassian.net/browse/NAE-1737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1737] Bug i18n field placeholder

---

projects/netgrif-components/src/lib/data-fields/text-field/rich-textarea-field/easymde-wrapper/easymde-wrapper.component.ts

- fix
- spellChecker: false
Fixes [NAE-1736]
[NAE-1736]: https://netgrif.atlassian.net/browse/NAE-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1736] Rich textarea fix cursor

---

projects/netgrif-components-core/src/lib/data-fields/i18n-field/models/i18n-field.ts

Implemented check for undefined translations.
Fixes [NAE-1741]
[NAE-1741]: https://netgrif.atlassian.net/browse/NAE-1741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1741] 'Undefined' error on frontend when checking i18n translation equality

---

projects/netgrif-components/nae-theme.scss
projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-icon-field/enumeration-icon-field.component.html
projects/netgrif-components/src/lib/data-fields/file-field/file-field.component.scss
projects/netgrif-components/src/lib/data-fields/number-field/number-currency-field/number-currency-field.component.html
projects/netgrif-components/src/lib/data-fields/number-field/number-currency-field/number-currency-field.component.scss

Added prefix to currency number field to display currency code, when editing the value.
Fixes [NAE-1739]
[NAE-1739]: https://netgrif.atlassian.net/browse/NAE-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1739] Currency symbol is displayed on new line, when editing currency field

---

projects/netgrif-components-core/src/lib/data-fields/file-field/abstract-file-field.component.ts

- fix
Fixes [NAE-1743]
[NAE-1743]: https://netgrif.atlassian.net/browse/NAE-1743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1743] File preview  change to null  object

---

projects/netgrif-components-core/src/lib/resources/engine-endpoint/public/public-task-resource.service.ts

- fix
Fixes [NAE-1744]
[NAE-1744]: https://netgrif.atlassian.net/browse/NAE-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1744] Public view does not work delete file

---

projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/abstract-enumeration-autocomplete-select-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html

- fix
Fixes [NAE-1745]
[NAE-1745]: https://netgrif.atlassian.net/browse/NAE-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1745] Enumeration autocomplete constantly sending value

---

projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-autocomplete-field/abstract-multichoice-autocomplete-field-component.component.ts
projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts

Fixes [NAE-1766]
[NAE-1766]: https://netgrif.atlassian.net/browse/NAE-1766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1766] Options on multichoice autocomplete do not refresh in a specific situation

---

projects/netgrif-components-core/src/lib/data-fields/enumeration-field/abstract-enumeration-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/abstract-enumeration-autocomplete-select-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/enumeration-field/models/enumeration-field.ts
projects/netgrif-components-core/src/lib/task/services/task-data.service.ts
projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-autocomplete-select-field/enumeration-autocomplete-select-field.component.html

Fixes [NAE-1760]
[NAE-1760]: https://netgrif.atlassian.net/browse/NAE-1760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1760] Enumeration autocomplete constantly sending value 

---

projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.ts
projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.html

Added validation check for empty array.
Fixes [NAE-1803]
| OS                  |   macOS Ventura 13.0        |
[NAE-1803]: https://netgrif.atlassian.net/browse/NAE-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1803] UserListComponent validations bug

---

projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.spec.ts
projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.ts
projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-value.spec.ts
projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-value.ts
projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.html
projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.ts

Refactored value type for user field list to Map.
Fixes [NAE-1804]
| OS                  |   macOS Ventura 13.0        |
[NAE-1804]: https://netgrif.atlassian.net/browse/NAE-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1804] In UserList field can choose one user multiple times

---

projects/netgrif-components-core/src/lib/task/services/assign-policy.service.ts
projects/netgrif-components-core/src/lib/user/services/user.service.ts
projects/netgrif-components-core/src/lib/utility/tests/mocks/mock-user.service.ts

Added race to update user before check for permissions.
Fixes [NAE-1839]
| OS                  |   macOS Ventura 13.1        |
[NAE-1839]: https://netgrif.atlassian.net/browse/NAE-1839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1839] Public view - fields after auto assign are still only visible

---

projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.spec.ts
projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.spec.ts
projects/netgrif-components-core/src/lib/data-fields/user-list-field/models/user-list-field.ts
projects/netgrif-components-core/src/lib/task-content/services/field-converter.service.ts
projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.spec.ts

Added roles attribute to user list field.
Implements [NAE-1874]
This was tested manually, and with unit tests.
| OS                  |   macOS Ventura 13.1        |
[NAE-1874]: https://netgrif.atlassian.net/browse/NAE-1874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1874] Filtering users based on roles when selecting users for UserListField

---

projects/netgrif-components-core/src/lib/view/workflow-view/abstract-workflow-view.component.ts

Fixed process list not being refreshed after clicking off the side panel when uploading
Fixes [NAE-1889]
Manually and with unit tests
| OS                  |     Linux Mint 21.1 Cinnamon      |
| Runtime             |     Node 19.9.0      |
| Dependency Manager  |    NPM 9.6.3       |
| Framework version   |      Angular 13.3.1     |
[NAE-1889]: https://netgrif.atlassian.net/browse/NAE-1889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1889] Process list is not refreshed after uploading process file

---

projects/netgrif-components-core/src/lib/filter/models/case-search-request-body.ts
projects/netgrif-components-core/src/lib/filter/models/task-search-request-body.ts
projects/netgrif-components-core/src/lib/resources/interface/case-get-request-body.ts
projects/netgrif-components-core/src/lib/view/case-view/service/case-view-service.ts
projects/netgrif-components-core/src/lib/view/case-view/tabbed-case-view.ts

- add new feature, tags, to request bodies
<Implements [NAE-1918]>
none
manually
| OS                  |   LinuxMint        |
| Runtime             |     NodeJS      |
| Dependency Manager  |     NPM      |
| Framework version   |    Angular13       |
[NAE-1918]: https://netgrif.atlassian.net/browse/NAE-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1918] Tags on process resources

---

projects/netgrif-components-core/src/lib/data-fields/user-field/abstract-user-field.component.ts
projects/netgrif-components/src/lib/data-fields/user-field/user-field.component.html

- add cross icon to remove selected user
Fixes [NAE-1921]
no new dependencies
manually
| OS                  |  LINUX MINT  20.3       |
| Runtime             |    NodeJS 14.21.3       |
| Dependency Manager  |    NPM  6.14.18      |
[NAE-1921]: https://netgrif.atlassian.net/browse/NAE-1921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1921] User field value cannot be cleared

---

projects/netgrif-components-core/src/lib/panel/task-panel/abstract-task-panel.component.ts
projects/netgrif-components/src/lib/panel/task-panel-list-pagination/task-list-pagination.component.html

Fixes [NAE-1925]
none
<Depends on #207>
manually
| OS                  |  LINUX MINT  20.3       |
| Runtime             |    NodeJS 14.21.3       |
| Dependency Manager  |    NPM  6.14.18      |
[NAE-1925]: https://netgrif.atlassian.net/browse/NAE-1925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …

[NAE-1925] Panel is not opening

---

projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts

- fix the issiue with sending more data requests
Fixes [NAE-1924]
none
depends on [NAE-1906], PR #207
manually thought nets
| OS                  |  LINUX MINT  20.3       |
| Runtime             |    NodeJS 14.21.3       |
| Dependency Manager  |    NPM  6.14.18      |
[NAE-1924]: https://netgrif.atlassian.net/browse/NAE-1924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NAE-1906]: https://netgrif.atlassian.net/browse/NAE-1906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1924] Neziadane volanie setData z FE

---

projects/netgrif-components-core/src/lib/tabs/classes/tab-view.ts

Fixes [NAE-1926]
none
Depends on #(207)
manually
| OS                  |    Linux min 20.3       |
| Runtime             |    nodeJS  14.21.3    |
| Dependency Manager  |   npm 6.14.18        |
| Framework version   |   angular 13        |
[NAE-1926]: https://netgrif.atlassian.net/browse/NAE-1926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1926] Can't close Tab in Tab view

---

projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components-core/src/lib/data-fields/user-list-field/abstract-user-list-field.component.ts
projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.html
projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-field.component.ts

Implements [NAE-1933]
No new dependencies introduced.
No new dependencies introduced.
| OS                  |   macOS Ventura 14.0        |
[NAE-1933]: https://netgrif.atlassian.net/browse/NAE-1933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1933] UserList deleteAll button

---

projects/nae-example-app/src/app/app.module.ts
projects/netgrif-components-core/src/lib/data-fields/i18n-field/i18n-text-field/abstract-i18n-text-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/i18n-field/models/i18n-field.ts
projects/netgrif-components-core/src/lib/data-fields/user-list-field/user-list-default-field/abstract-user-list-default-field.component.ts
projects/netgrif-components-core/src/lib/side-menu/content-components/user-assign/abstract-multi-user-assign.component.ts
projects/netgrif-components/nae-theme.scss
projects/netgrif-components/src/lib/data-fields/data-field.theme.scss
projects/netgrif-components/src/lib/data-fields/user-field/user-default-field/user-default-field.component.html
projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-default-field/user-list-default-field.component.html
projects/netgrif-components/src/lib/dialog/multi-user-assign-dialog/multi-user-assign-dialog.component.ts

Fixes [NAE-1948]
| OS                  |   macOS Ventura 14.0        |
[NAE-1948]: https://netgrif.atlassian.net/browse/NAE-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1948] Bugs after merge to 6.4.0

---

projects/netgrif-components-core/src/lib/data-fields/case-ref-field/case-ref-default/case-ref-default.component.ts
projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-caseref-field/abstract-enumeration-caseref-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-icon-field/abstract-enumeration-icon-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/enumeration-field/enumeration-stepper-field/abstract-enumeration-stepper-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/models/abstract-data-field.ts
projects/netgrif-components-core/src/lib/data-fields/multichoice-field/multichoice-caseref-field/abstract-multichoice-caseref-field.component.ts
projects/netgrif-components-core/src/lib/data-fields/string-collection-field/string-collection-default-field/abstract-string-collection-default-field.component.ts
projects/netgrif-components/src/lib/data-fields/button-field/button-default-field/button-default-field.component.html
projects/netgrif-components/src/lib/data-fields/button-field/button-default-field/button-default-field.component.ts
projects/netgrif-components/src/lib/data-fields/enumeration-field/enumeration-icon-field/enumeration-icon-field.component.html

- change checking of properties in components
Implements [NAE-1958]
none
manually
| OS                  |     LinuxMint 20      |
[NAE-1958]: https://netgrif.atlassian.net/browse/NAE-1958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1958] Make component properties changeable

---

projects/netgrif-components-core/src/lib/task-content/services/task-content.service.ts
projects/netgrif-components/src/lib/data-fields/i18n-field/i18n-divider-field/i18n-divider-field.component.html

Fixes [NAE-20123]
| OS                  |   macOS Sequoia 15.0        |
| Runtime             |  Node 20.17.0         |
| Dependency Manager  |  NPM 10.8.2        |

[NAE-2013] Autocomplete options are set to the first dropdown

---

projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-default-field/user-list-default-field.component.html

Fixes issue with userlists.
Fixes [NAE-2018]
| OS                  |   macOS Sequoia 15.0        |
| Runtime             |  Node 20.17.0         |
| Dependency Manager  |  NPM 10.8.2        |
[NAE-2018]: https://netgrif.atlassian.net/browse/NAE-2018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-2018] User list input is not showing dialog

---

projects/netgrif-components/src/lib/dialog/new-case-dialog/new-case-dialog.component.scss
projects/netgrif-components/src/lib/user/profile/profile.component.html
projects/netgrif-components/src/lib/user/profile/profile.component.scss

- fix profile
- fix padding new case
Fixes [NAE-2019]
Manually
| OS                  |   macOS …

[NAE-2019] Bugs after merge with 6.4.0

---

projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components-core/src/lib/panel/abstract/panel-with-immediate-data.ts
projects/netgrif-components/src/lib/data-fields/user-field/user-default-field/user-default-field.component.html
projects/netgrif-components/src/lib/data-fields/user-field/user-default-field/user-default-field.component.scss
projects/netgrif-components/src/lib/data-fields/user-list-field/user-list-default-field/user-list-default-field.component.html
projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.html
projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.scss
projects/netgrif-components/src/lib/navigation/navigation-double-drawer/navigation-double-drawer.component.ts

Fixes [NAE-2022]
- <Name of a test [test file](link to the test file)>
| OS                  | …

[NAE-2022] UI Design Fixes and Improvements

---

projects/netgrif-components-core/src/assets/i18n/de.json
projects/netgrif-components-core/src/assets/i18n/en.json
projects/netgrif-components-core/src/assets/i18n/sk.json
projects/netgrif-components-core/src/lib/admin/role-assignment-ldap-group/abstract-ldap-group-role-assignment.component.ts
projects/netgrif-components-core/src/lib/admin/role-assignment/abstract-role-assignment.component.ts
projects/netgrif-components-core/src/lib/admin/role-assignment/services/ProcessList.ts
projects/netgrif-components-core/src/lib/admin/user-invite/abstract-user-invite.component.ts
projects/netgrif-components/src/lib/admin/ldap-group-role-assignment/ldap-group-role-assignment.component.html
projects/netgrif-components/src/lib/admin/role-assignment/role-assignment.component.html
projects/netgrif-components/src/lib/admin/user-invite/user-invite.component.html
projects/netgrif-components/src/lib/admin/user-invite/user-invite.component.scss
projects/netgrif-components/src/lib/data-fields/data-field.theme.scss

- add frontend search of processes to role, ldap and user assignment components
Implements [NAE-2040]
none
manually
| OS                  |      Mint 22     |
| Runtime             |      Node 20.18.0     |
| Dependency Manager  |      Npm   10.8.2   |
[NAE-2040]: https://netgrif.atlassian.net/browse/NAE-2040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[NAE-2040] - Search in role management

---

projects/netgrif-components-core/src/lib/resources/engine-endpoint/petri-net-resource.service.ts
projects/netgrif-components-core/src/lib/resources/interface/petri-net-request-body.ts
projects/netgrif-components-core/src/lib/view/workflow-view/abstract-workflow-view.component.ts
projects/netgrif-components-core/src/lib/view/workflow-view/workflow-view.service.ts
projects/netgrif-components/src/lib/view/workflow-view/workflow-view.component.html
projects/netgrif-components/src/lib/view/workflow-view/workflow-view.component.scss
projects/netgrif-components/src/lib/view/workflow-view/workflow-view.component.spec.ts

- add search to workflow view
- add search method to PetriNetResourceService
Implements [NAE-2039]
none
manually
| OS                  |      Mint 22     |
| Runtime             |      Node 20.18.0     |
| Dependency Manager  |      Npm   10.8.2   |
[NAE-2039]: https://netgrif.atlassian.net/browse/NAE-2039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-2039] Search in workflow view

---

projects/netgrif-components-core/src/lib/data-fields/case-ref-field/model/abstract-case-ref-base-field-component.ts
projects/netgrif-components-core/src/lib/header/abstract-header.component.spec.ts
projects/netgrif-components-core/src/lib/header/abstract-header.component.ts
projects/netgrif-components-core/src/lib/panel/task-panel-list/task-panel-list-pagination/abstract-task-list-pagination.component.ts
projects/netgrif-components-core/src/lib/view/case-view/components/case-list-paginator/abstract-case-list-paginator.component.ts
projects/netgrif-components-core/src/lib/view/case-view/service/case-view-service.ts
projects/netgrif-components/src/lib/header/header.component.ts

- add all functionality from branch NAE2047 to another release
Implements [NAE-2057]
none
manually
| OS                  |      LinuxMint   22  |
| Runtime             |      Node 20.18.0     |
| Dependency Manager  |      NPM 10.8.2     |
| Framework version   |     Angular 13.3.1      |
[NAE-2057]: https://netgrif.atlassian.net/browse/NAE-2057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-2057] Fix NAE-2047 in release 6.4.1

---

projects/netgrif-components-core/src/lib/navigation/dashboard/abstract-dashboard.component.ts

Some small fixes found in testing. 
Implements [NAE-2063]
It was tested by new dashboard_management_test.xml included in project
| OS                  |      Windows 11     |
| Runtime             |     Node v22.14.0     |
| Dependency Manager  |    NPM 10.9.2       |
| Framework version   |     Angular  13.3.1    |
[NAE-2063]: https://netgrif.atlassian.net/browse/NAE-2063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-2063] Action API 6.5.0
